In [1]:
import pandas as pd

In [19]:
df = pd.read_excel('z.xlsx',usecols=[50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65])

In [20]:
df

,核心课程第1节作业,核心课程第2节作业,核心课程第3节作业,核心课程第4节作业,核心课程第5节作业,核心课程第6节作业,核心课程第7节作业,核心课程第8节作业,核心课程第9节作业,核心课程第10节作业,核心课程第11节作业,核心课程第12节作业,核心课程第13节作业,核心课程第14节作业,核心课程第15节作业,核心课程第16节作业
0,67,33,1000,2000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
1,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
2,1000,1000,0,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
3,67,33,75,2000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
4,2000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,67,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
58,34,66,1000,2000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
59,100,66,75,2000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
60,100,66,2000,2000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
61,1000,1000,2000,2000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000

In [24]:
df = df.replace(1000,0)

In [26]:
df = df.replace(2000,0)

In [30]:
df.apply(lambda x : x.value_counts().get(0,0),axis=0)

核心课程第1节作业     30
核心课程第2节作业     41
核心课程第3节作业     47
核心课程第4节作业     59
核心课程第5节作业     62
核心课程第6节作业     62
核心课程第7节作业     62
核心课程第8节作业     62
核心课程第9节作业     62
核心课程第10节作业    62
核心课程第11节作业    62
核心课程第12节作业    62
核心课程第13节作业    62
核心课程第14节作业    62
核心课程第15节作业    62
核心课程第16节作业    62
dtype: int64

In [31]:
df

,核心课程第1节作业,核心课程第2节作业,核心课程第3节作业,核心课程第4节作业,核心课程第5节作业,核心课程第6节作业,核心课程第7节作业,核心课程第8节作业,核心课程第9节作业,核心课程第10节作业,核心课程第11节作业,核心课程第12节作业,核心课程第13节作业,核心课程第14节作业,核心课程第15节作业,核心课程第16节作业
0,67,33,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,67,33,75,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,67,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
58,34,66,0,0,0,0,0,0,0,0,0,0,0,0,0,0
59,100,66,75,0,0,0,0,0,0,0,0,0,0,0,0,0
60,100,66,0,0,0,0,0,0,0,0,0,0,0,0,0,0
61,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0